import type { Metadata } from "next";
import { Noto_Sans_KR } from "next/font/google";
import { CustomHeader } from "@/components/CustomHeader";
import "./globals.css";


const NotoSans = Noto_Sans_KR({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${NotoSans.className}`}
      >
        <CustomHeader />
        <main className="w-3/4 mx-auto mt-14">
          {children}
        </main>
      </body>
    </html>
  );
}
